services:
    _defaults:
        autowire: true
        autoconfigure: true

    Mcfedr\JsonFormBundle\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    Mcfedr\JsonFormBundle\Controller\JsonController:
        public: true
